class_name Enums

enum ActionEvent {
	AREA_INTERVAL = 0,
	AREA_EMPTY = 1,
	BODY_ENTER = 10,
	BODY_EXIT = 11,
	BODY_INTERVAL = 12,
	BUTTON_PRESS = 20,
	BUTTON_RELEASE = 21,
	ENTITY_DAMAGE = 35,
	ENTITY_DEATH = 33,
	ENTITY_EQUIP = 34,
	ENTITY_PICKUP = 30,
	ENTITY_READY = 32,
	ENTITY_USE = 31,
	LEVEL_LOAD = 70,
	LEVEL_COMPLETE = 71,
	OBJECTIVE_COMPLETE = 50,
	RAYCAST_COLLISION = 60,
	TIMER_TIMEOUT = 40,
	VISION_SEEN = 80,
	VISION_HIDDEN = 81,
}

enum CRUD {
	## Synonym for create
	ADD = 0,
	CREATE = 0,
	# READ?
	UPDATE = 2,
	DELETE = 3,
	## Synonym for delete
	REMOVE = 3,
}

enum Tristate {
	UNSET = -1,
	FALSE = 0,
	TRUE = 1,
}
